# Generated by Django 4.0.1 on 2023-01-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_participant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lati_tude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='longi_tude',
            field=models.FloatField(default=0.0),
        ),
    ]
