# Generated by Django 4.0.1 on 2023-01-09 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0013_product_lati_tude_product_longi_tude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
