# Generated by Django 4.0.1 on 2023-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_product_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='noc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
