# Generated by Django 4.0.1 on 2023-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_paypal_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='len_ght',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wid_th',
            field=models.IntegerField(null=True),
        ),
    ]
